// IW7 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

_id_DF0C()
{
    scripts\aitypes\bt_util::init();
    behaviortree\slasher::_id_DEE8();
    scripts\asm\slasher_dlc4\mp\states::_id_2371();
    scripts\mp\agents\slasher\slasher_tunedata::setuptunedata();
    thread _id_FAB0();
}

_id_FAB0()
{
    scripts\mp\agents\slasher\slasher_agent::_id_FAB0();
    level.agent_funcs["slasher"]["on_damaged"] = ::onslasherdamaged;
    level.agent_funcs["slasher"]["on_killed"] = ::onslasherkilled;
    level._id_18EE["slasher"]["setup_func"] = ::setup_slasher_dlc4_agent;

    if ( !isdefined( level.damage_feedback_overrride ) )
        level.damage_feedback_overrride = [];

    level.damage_feedback_overrride["slasher"] = scripts\cp\maps\cp_final\cp_final_damage::slasher_processdamagefeedback;

    if ( !isdefined( level._id_8CBD ) )
        level._id_8CBD = [];

    level._id_8CBD["slasher"] = ::calculateslasherhealth;
}

setup_slasher_dlc4_agent()
{
    scripts\mp\agents\slasher\slasher_agent::_id_FA8A();
    self.spawn_round_num = level._id_13BD3;
    self.not_affected_by_traps = 1;
}

calculateslasherhealth()
{
    return 30000;
}

onslasherdamaged( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11 )
{
    var_12 = var_2;
    var_2 = min( var_2, 300 );

    if ( isdefined( self.nodamagescale ) )
        var_2 = var_12;

    scripts\cp\maps\cp_final\cp_final_damage::cp_final_onzombiedamaged( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11 );
}

onslasherkilled( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 )
{
    self _meth_8096( "weapon_zmb_slasher_vm", "tag_weapon_right" );
    self._id_C026 = 1;

    if ( isdefined( level.slasher_loot_func ) )
        self [[ level.slasher_loot_func ]]( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 );

    var_9 = 1000;

    foreach ( var_11 in level.players )
    {
        if ( var_11 _id_0A77::_id_9D05() )
            var_11 _id_0A63::_id_82F9( var_9 );
    }

    scripts\mp\mp_agent::_id_5006( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 );
}
