// IW7 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

main()
{
    setup_callbacks();
    _id_F8E1();
}

setup_callbacks()
{
    level.bot_funcs["dropped_weapon_think"] = ::_id_10441;
    level.bot_funcs["dropped_weapon_cancel"] = ::_id_10448;
    level.bot_funcs["crate_low_ammo_check"] = ::_id_10444;
    level.bot_funcs["crate_should_claim"] = ::_id_10445;
    level.bot_funcs["crate_wait_use"] = ::_id_10446;
    level.bot_funcs["crate_in_range"] = ::_id_10443;
    level.bot_funcs["crate_can_use"] = ::_id_10442;
}

_id_F8E1()
{
    level.bots_gametype_handles_class_choice = 1;
}

_id_10448( var_0 )
{
    if ( scripts\mp\bots\bots_util::_id_2DB8() > 0 )
    {
        var_1 = scripts\mp\utility\game::_id_8225( self getcurrentweapon() );

        if ( isdefined( var_0._id_C270 ) )
        {
            var_2 = var_0._id_C270.classname;

            if ( scripts\engine\utility::string_starts_with( var_2, "weapon_" ) )
                var_2 = getsubstr( var_2, 7 );

            var_3 = scripts\mp\utility\game::_id_8225( var_2 );

            if ( !_id_2ED7( var_1, var_3 ) )
                return 1;
        }
    }

    if ( !isdefined( var_0._id_C270 ) )
        return 1;

    return 0;
}

_id_10441()
{
    self notify( "bot_think_seek_dropped_weapons" );
    self endon( "bot_think_seek_dropped_weapons" );
    self endon( "death" );
    self endon( "disconnect" );
    level endon( "game_ended" );

    for (;;)
    {
        var_0 = 0;

        if ( self [[ level.bot_funcs["should_pickup_weapons"] ]]() && !scripts\mp\bots\bots_util::bot_is_remote_or_linked() )
        {
            if ( scripts\mp\bots\bots_util::_id_2E3B() )
            {
                var_1 = getentarray( "dropped_weapon", "targetname" );
                var_2 = scripts\engine\utility::_id_782F( self.origin, var_1 );

                if ( var_2.size > 0 )
                {
                    var_3 = var_2[0];
                    scripts\mp\bots\bots::_id_2E6F( var_3 );
                }
            }
            else
            {
                var_1 = getentarray( "dropped_weapon", "targetname" );
                var_2 = scripts\engine\utility::_id_782F( self.origin, var_1 );

                if ( var_2.size > 0 )
                {
                    var_4 = self getnearestnode();

                    if ( isdefined( var_4 ) )
                    {
                        var_5 = scripts\mp\utility\game::_id_8225( self getcurrentweapon() );

                        foreach ( var_3 in var_2 )
                        {
                            var_7 = var_3.classname;

                            if ( scripts\engine\utility::string_starts_with( var_7, "weapon_" ) )
                                var_7 = getsubstr( var_7, 7 );

                            var_8 = scripts\mp\utility\game::_id_8225( var_7 );

                            if ( _id_2ED7( var_5, var_8 ) )
                            {
                                if ( !isdefined( var_3._id_370E ) || !var_3._id_370E )
                                {
                                    var_3._id_BE7C = getclosestnodeinsight( var_3.origin );
                                    var_3._id_370E = 1;
                                }

                                if ( isdefined( var_3._id_BE7C ) && nodesvisible( var_4, var_3._id_BE7C, 1 ) )
                                {
                                    scripts\mp\bots\bots::_id_2E6F( var_3 );
                                    break;
                                }
                            }
                        }
                    }
                }
            }
        }

        wait( randomfloatrange( 0.25, 0.75 ) );
    }
}

_id_2E60( var_0 )
{
    var_1 = 0;

    switch ( var_0 )
    {
        case "weapon_other":
        case "weapon_explosive":
        case "weapon_grenade":
        case "weapon_projectile":
            break;
        case "weapon_pistol":
            var_1 = 1;
            break;
        case "weapon_dmr":
        case "weapon_sniper":
            var_1 = 2;
            break;
        case "weapon_shotgun":
        case "weapon_lmg":
        case "weapon_assault":
        case "weapon_smg":
            var_1 = 3;
            break;
    }

    return var_1;
}

_id_2ED7( var_0, var_1 )
{
    var_2 = _id_2E60( var_0 );
    var_3 = _id_2E60( var_1 );
    return var_3 > var_2;
}

_id_10444()
{
    var_0 = self getcurrentweapon();
    var_1 = self getweaponammoclip( var_0 );
    var_2 = self getweaponammostock( var_0 );
    var_3 = weaponclipsize( var_0 );
    return var_1 + var_2 < var_3 * 0.25;
}

_id_10445()
{
    return 0;
}

_id_10446()
{
    scripts\mp\bots\bots_util::_id_2ECC( 5000 );
}

_id_10443( var_0 )
{
    return 1;
}

_id_10442( var_0 )
{
    if ( scripts\mp\bots\bots::crate_can_use_always( var_0 ) )
    {
        if ( isdefined( var_0 ) && isdefined( var_0._id_2EFA ) && scripts\engine\utility::array_contains( var_0._id_2EFA, self ) )
        {
            if ( scripts\mp\bots\bots_util::_id_2E3B() )
                return 1;
            else
                return 0;
        }

        var_1 = scripts\mp\utility\game::_id_8225( self getcurrentweapon() );

        if ( _id_2E60( var_1 ) <= 1 )
            return 1;

        if ( _id_10444() )
            return 1;

        return 0;
    }

    return 0;
}
