// IW7 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

_id_DF0C()
{
    scripts\aitypes\bt_util::init();
    behaviortree\crab_brute::_id_DEE8();
    scripts\asm\crab_brute\mp\states::_id_2371();
    scripts\mp\agents\crab_brute\crab_brute_tunedata::setuptunedata();
    thread _id_FAB0();
}

_id_FAB0()
{
    level endon( "game_ended" );

    if ( !isdefined( level._id_18EE ) )
        level waittill( "scripted_agents_initialized" );

    level._id_18EE["crab_brute"]["setup_func"] = ::_id_FA8A;
    level._id_18EE["crab_brute"]["setup_model_func"] = ::_id_FACE;
    level.agent_funcs["crab_brute"]["on_damaged"] = scripts\cp\maps\cp_town\cp_town_damage::cp_town_onzombiedamaged;

    if ( !isdefined( level._id_8CBD ) )
        level._id_8CBD = [];

    level._id_8CBD["crab_brute"] = ::calculatecrabbruteihealth;
    level.agent_funcs["crab_brute"]["gametype_on_killed"] = ::_id_C4D1;
    level.brute_loot_check = [];

    if ( !isdefined( level.damage_feedback_overrride ) )
        level.damage_feedback_overrride = [];

    level.damage_feedback_overrride["crab_brute"] = scripts\cp\maps\cp_town\cp_town_damage::crog_processdamagefeedback;

    if ( !isdefined( level.special_zombie_damage_func ) )
        level.special_zombie_damage_func = [];

    level.special_zombie_damage_func["crab_brute"] = ::crab_brute_special_damage_func;
}

_id_FACE( var_0 )
{
    self setmodel( "zmb_brutecrab" );
}

setupzombiegametypevars()
{
    self.class = undefined;
    self._id_BCF6 = undefined;
    self._id_26B9 = undefined;
    self.guid = undefined;
    self.name = undefined;
    self._id_EB6A = undefined;
    self._id_CA5B = undefined;
    self._id_13CA0 = undefined;
    self._id_C2AD = undefined;
    self._id_0291 = undefined;
    self.sessionstate = undefined;
    self._id_55E6 = undefined;
    self._id_55E9 = undefined;
    self._id_55D9 = undefined;
    self._id_55E4 = 1;
    self._id_C026 = undefined;
    self._id_0184 = 0;
    self._id_0180 = 0;
    self._id_116D4 = undefined;
    self._id_441A = undefined;
    self._id_4B82 = undefined;
    self._id_5793 = undefined;
    self._id_37FD = 0;
    self._id_24CA = undefined;
    self._id_6622 = 0;
    self._id_B36E = undefined;
    self._id_126A3 = undefined;
    self._id_8C35 = 0;
    self.attackent = undefined;
    self._id_9342 = 1;
    self._id_1B03 = "idle";
    self._id_01F5 = "walk";
    self._id_0293 = 100;
    self.radius = 15;
    self.height = 40;
    self._id_252B = 26 + self.radius;
    self._id_B640 = "normal";
    self._id_B641 = 50;
    self._id_2539 = 54;
    self._id_253A = -64;
    self._id_4D45 = 2250000;
    self._id_0181 = 1;
    self.guid = self getentitynumber();
    self._id_BCE4 = 1.0;
    self._id_C081 = 1.0;
    self._id_126E8 = 1.0;
    self._id_772A = 1.0;
    self._id_2AB2 = 0;
    self._id_2AB8 = 1;
    self._id_118FC = 0;
    self._id_002F = 1;
    self._id_B5F9 = 40;
    self._id_B62E = 70;
    self._id_B631 = 80;
    self._id_B62F = squared( self._id_B62E );
    self._id_503C = self.radius + 1;
    self._id_B607 = 0.5;
    self._id_565C = 0;
    self._id_9BAC = 0;
    self._id_54CB = 0;
    self.damaged_by_player = 0;
    self._id_9E0C = undefined;
    self._id_6F73 = undefined;
    self._id_B0FC = 1;
    self._id_74B5 = 0;
    self._id_012E = undefined;
    self._id_E821 = undefined;
    self._id_A8A2 = [];
    self._id_8C12 = 0;
    self._id_8C14 = undefined;
    self._id_9BA7 = undefined;
    self._id_0179 = 200;
    self._id_4E4C = undefined;
    self._id_10A57 = undefined;
    self._id_828A = undefined;
    self._id_CE65 = undefined;
    self._id_29D2 = 1;
    self.vignette_nocorpse = undefined;
    self.death_anim_no_ragdoll = undefined;
    self.dont_cleanup = 1;
    self._id_594C = 1;
    self.spawn_round_num = level._id_13BD3;

    if ( getdvarint( "scr_zombie_left_foot_sharp_turn_only", 0 ) == 1 )
        self._id_AB3F = 1;
}

_id_FA8A()
{
    setupzombiegametypevars();
    self.height = self._id_18F4;
    self.radius = self._id_18F9;
    self._id_9341 = 1;
    self._id_B62D = 70;
    self._id_B62E = 70;
    self._id_B631 = 80;
    self._id_B62F = squared( self._id_B62E );
    self._id_503C = self.radius + 1;
    self._id_B607 = 0.5;
    self._id_B601 = 45;
    self._id_504E = 55;
    self._id_129AF = 55;
    self._id_0368 = -60;
    self._id_0100 = 60;
    self _meth_84E6( 45 );
    self.ground_pound_damage = 50;
    self._id_013C = 2500;
    self._id_013E = 2500;
    self._id_013D = 2500;
    self._id_0180 = 1;
    self _meth_85C9( 16 );
    thread dopostspawnupdates();
    thread listen_for_death_sfx();
}

dopostspawnupdates()
{
    wait 0.5;
    self.dont_cleanup = 1;
}

listen_for_death_sfx()
{
    self waittill( "death" );
    self playsound( "brute_crog_death" );
    wait 1;
    self playsound( "brute_crog_explo" );
}

getenemy()
{
    if ( isdefined( self.myenemy ) )
        return self.myenemy;

    return undefined;
}

lookatenemy()
{
    var_0 = getenemy();

    if ( isdefined( var_0 ) )
    {
        var_1 = var_0.origin - self.origin;
        var_2 = vectortoangles( var_1 );
        self orientmode( "face angle abs", var_2 );
    }
    else
        self orientmode( "face angle abs", self.angles );
}

crab_brute_special_damage_func( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11 )
{
    if ( scripts\asm\asm::_id_2354( "burrow_loop" ) )
        return 0;

    if ( var_5 == "gas_grenade_mp" )
        return 0;

    self._id_A96A = gettime();

    if ( isdefined( var_7 ) )
    {
        var_12 = scripts\mp\agents\crab_brute\crab_brute_tunedata::gettunedata();
        var_13 = anglestoforward( self.angles ) * -1;
        var_14 = vectordot( var_13, var_7 );

        if ( var_14 > var_12.reduce_damage_dot )
        {
            var_2 = var_2 * var_12.reduce_damage_pct;
            self.armor_hit = 1;
        }
    }

    return var_2;
}

_id_C4D1( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11 )
{
    if ( isdefined( self.agent_type ) && self.agent_type == "crab_brute" )
        var_1 _id_0A5E::_id_D9AD( "mt_dlc3_crab_brute" );

    var_12 = scripts\engine\utility::_id_DC6B( [ "ammo_max", "instakill_30", "cash_2", "instakill_30", "cash_2", "instakill_30", "cash_2" ] );

    if ( isdefined( var_12 ) && !isdefined( self._id_72AC ) )
    {
        if ( !isdefined( level.brute_loot_check[self.spawn_round_num] ) )
        {
            level.brute_loot_check[self.spawn_round_num] = 1;
            level thread _id_0A76::_id_5CF6( self.origin, var_1, var_12 );
        }
    }

    var_13 = 400;
    level thread boss_death_vo();

    foreach ( var_15 in level.players )
        var_15 _id_0A63::_id_82F9( var_13 );
}

boss_death_vo()
{
    wait 10;

    if ( isdefined( level.elvira_ai ) )
        level thread _id_0A6A::_id_12885( "ww_crog_defeat_elvira", "rave_announcer_vo", "highest", 70, 0, 0, 1 );
    else
        level thread _id_0A6A::_id_12885( "ww_crog_defeat_generic", "rave_announcer_vo", "highest", 70, 0, 0, 1 );
}

calculatecrabbruteihealth()
{
    return 5000 * level.players.size;
}

shouldignoreenemy( var_0 )
{
    if ( !isalive( var_0 ) )
        return 1;

    if ( var_0._id_0184 || isdefined( var_0.owner ) && var_0.owner._id_0184 )
        return 1;

    if ( _id_0F74::_id_1002C( var_0 ) )
        return 1;

    return 0;
}

create_brute_death_fx( var_0 )
{
    self._id_CE65 = 1;
}
