// IW7 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

_id_DF0C()
{
    scripts\aitypes\bt_util::init();
    behaviortree\zombie_dlc4::_id_DEE8();
    scripts\asm\zombie_dlc4\mp\states::_id_2371();

    if ( !isdefined( level._id_10970 ) )
        level._id_10970 = [];

    level._id_18EE["generic_zombie"]["asm"] = "zombie_dlc4";
    level._id_18EE["generic_zombie"]["behaviorTree"] = "zombie_dlc4";
    level._id_18EE["generic_zombie"]["animclass"] = "zombie_dlc4_animclass";
    level._id_13BDC = 1;
    level._id_4878 = 0;
    level._id_BF7C = 0;
    level._id_BCCE = [];
    level._id_BCE5 = [];
    level._id_C082 = [];
    level._id_126E9 = [];
    level._id_8EE6 = [];
    level._id_5662 = [];
    level._id_D437 = "allies";
    _id_0F72::_id_9890();
    _id_0F72::_id_98A5();
    _id_0F72::_id_97FB();
    _id_0F72::_id_AEB0();
    thread _id_FAB0();
    thread _id_0F72::_id_BC5C();
}

zombieinit_dlc()
{
    _id_0C75::_id_13F9A();
}

_id_FAB0()
{
    level endon( "game_ended" );

    if ( !isdefined( level._id_18EE ) )
        level waittill( "scripted_agents_initialized" );

    level._id_18EE["generic_zombie"]["setup_func"] = ::_id_FA8A;
    level._id_18EE["generic_zombie"]["setup_model_func"] = ::_id_FACE;
    level.agent_funcs["generic_zombie"]["gametype_on_damage_finished"] = _id_0CBC::_id_C5CE;
    level.agent_funcs["generic_zombie"]["gametype_on_killed"] = scripts\cp\maps\cp_final\cp_final_damage::cp_final_onzombiekilled;
    level.agent_funcs["generic_zombie"]["on_damaged"] = scripts\cp\maps\cp_final\cp_final_damage::cp_final_onzombiedamaged;
    level.agent_funcs["generic_zombie"]["on_damaged_finished"] = ::_id_C5CE;
    level.agent_funcs["generic_zombie"]["on_killed"] = ::_id_C5D2;
}

_id_FA8A()
{
    _id_0F72::_id_FA8A();
    self.kung_fu_punched = 0;
    self.pinched = undefined;
    self.fridge_trap_marked = undefined;

    if ( scripts\engine\utility::_id_9CEE( self.activated_venomx_sphere ) )
        self.activated_venomx_sphere = undefined;

    if ( scripts\engine\utility::_id_9CEE( self.dot_triggered ) )
        self.dot_triggered = undefined;
}

_id_FACE( var_0 )
{
    _id_0F72::_id_FACE();
}

dopiranhatrapdeath()
{
    scripts\asm\asm::_id_237C( "piranha_trap" );
}

_id_C5CE( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11, var_12 )
{
    _id_0F72::_id_C5CE( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11, var_12 );
}

_id_C5D2( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 )
{
    _id_0F72::_id_C5D2( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 );
}

_id_C4BD( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9 )
{
    _id_0F72::_id_C4BD( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9 );
}
